### PR TITLE
Version 5.2.0

### PR DESCRIPTION
**Pull request by sarthfrey**

### CODE REVIEW

**Comment by pfhayes** [comment]
is this urgent to get out, or can it wait to include @simonhowey 's upcoming changes?

**Comment by sarthfrey** [comment]
> is this urgent to get out, or can it wait to include @simonhowey 's upcoming changes?

I think it can wait, just put this out so it's ready

**Comment by oliviakim95** [comment]
> is this urgent to get out, or can it wait to include @simonhowey 's upcoming changes?

@pfhayes will we be waiting for simon's changes to release Lydia's metric minimization changes?

**Comment by sarthfrey** [comment]
It seems like #56 by @simonhowey has been merged, so this can go ahead

**Comment by simonhowey** [comment]
Blocked on:
https://github.com/sigopt/sigopt-java/pull/58

**Pull request merged**
