### PR TITLE
Link cacert in Travis CI build matrix for JDK9 and manually install oracle JDK8

### PR DESCRIPTION
**Pull request by sarthfrey**

### CODE REVIEW

**Comment by taylorjacklespriggs** [comment]
does not seem to work :( I think maybe this error is happening before we can do anything about it

**Comment by sarthfrey** [comment]
Fixed JDK 9! but a random JDK8 unrelated error has appeared which is very fun, `Expected feature release number in range of 9 to 14, but got: 8`

**Comment by sarthfrey** [comment]
https://github.com/travis-ci/travis-ci/issues/10290

wow, in this issue the proposed solution is to just use openjdk8!

**Comment by sarthfrey** [comment]
😎

**Comment by sarthfrey** [comment]
🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢

**Pull request merged**
